name: Trigger Vercel Cron Job

on:
  schedule:
    # Her 10 dakikada bir çalışır
    - cron: '*/10 * * * *'
  workflow_dispatch: # Manuel olarak tetikleme imkanı da sunar (test için)

jobs:
  trigger_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API Endpoint
        run: |
          curl -X GET \
          'https://activates.vercel.app/api/cron/check-presence' \
          -H 'Authorization: Bearer ${{ secrets.VERCEL_CRON_SECRET }}' \
          --fail # HTTP hata kodlarında (4xx, 5xx) başarısız sayar 